trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"

  - task: Npm@1
    inputs:
      command: "install"
    displayName: "npm install"

  - task: PublishPipelineArtifact@0
    inputs:
      ArtifactName: "drop"
