trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
      
  - task: Npm@1
    inputs:
      command: "install"
    displayName: "npm install"

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run prebuild'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'

  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: "public"
      ArtifactName: "drop"