name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run prebuild
          npm run build

      - name: Tar files
        run: tar -cjf /tmp/files.tbz public/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: /tmp/files.tbz

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.7
        with:
          name: node-app
      - name: Un-Tar files
        run: |
          tar -xjf files.tbz
          rm files.tbz
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: String replace bathpath in
        run: |
          find public -type f -name "*.html" | xargs sed -i -e 's/"\//"\/design-history\//g'
          find public -type f -name "*.json" | xargs sed -i -e 's/"\//"\/design-history\//g'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1